# Generated by Django 3.1 on 2022-04-02 15:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('adress', models.CharField(max_length=30, verbose_name='住所')),
                ('sort', models.IntegerField(choices=[(1, '飲食店'), (2, 'カフェ/喫茶店'), (3, '軽食'), (4, '自然'), (5, '施設')], verbose_name='種類')),
                ('image', models.ImageField(upload_to='', verbose_name='画像')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='名前')),
                ('text', models.TextField(verbose_name='内容')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('eva', models.BooleanField(verbose_name='超良かった')),
                ('image', models.ImageField(upload_to='', verbose_name='画像')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numazutourist.place')),
            ],
        ),
    ]
