# Generated by Django 3.1 on 2022-04-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numazutourist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='place',
            name='sort',
            field=models.IntegerField(choices=[(1, '飲食店'), (2, 'カフェ/喫茶店'), (3, '軽食'), (4, '自然'), (5, '施設'), (6, 'その他')], verbose_name='種類'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像'),
        ),
    ]
