# Generated by Django 3.1 on 2022-04-03 08:50

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('numazutourist', '0002_auto_20220403_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, verbose_name='曜日名')),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(6, '６以下の数字で入力してください'), django.core.validators.MinValueValidator(0, '0以上の数字で入力してください')], verbose_name='曜日コード')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='closetime',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='CLOSE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='explain',
            field=models.CharField(default='説明', max_length=140, verbose_name='施設詳細'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='opentime',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='OPEN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='place',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='place',
            name='adress',
            field=models.CharField(max_length=100, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='place',
            name='holidays',
            field=models.ManyToManyField(related_name='定休日', to='numazutourist.Weekday'),
        ),
    ]
