# Generated by Django 3.1 on 2022-04-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numazutourist', '0003_auto_20220403_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='holidays',
            field=models.ManyToManyField(blank=True, to='numazutourist.Weekday', verbose_name='定休日'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/shop', verbose_name='画像'),
        ),
    ]
