# Generated by Django 3.1 on 2022-04-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numazutourist', '0004_auto_20220403_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='numazutourist/', verbose_name='画像'),
        ),
    ]
